### ISSUE TITLE
Alert is not working with backend-updated branch 

### ISSUE THREAD

**Issue by ShilpaSivanesan** [grafana/datasource-plugin-genericdatasource#119]
Hi,
I am using simple JSON data source backend-updated branch and running JSON server for sending fake data.
There is an issue with alerting, it doesn't respect the time range from conditions and takes all the data points 

I have set condition as 

WHEN
avg ()
OF
query (A, 1m, now)
HAS NO VALUE

and I don't have value for last 1 hour, so expecting it to send alert for no data, but it does take whole dataset and so not sending any alert

**Comment by tamirhad** [comment]
hi,
did you managed to create alerts?

**Comment by AlexSemenovIRL** [comment]
Im looking for this feature also, any updates?

**Comment by itsgareth** [comment]
The Simple JSON Datasource is now deprecated, and as a result, we are closing all open issues in this repository.
Our development focus has shifted, and we are no longer actively maintaining this plugin.

This deprecation means that this plugin won’t receive any feature updates or bug fixes except critical security fixes.
After 6 months of the deprecation date (End of June 2024), no updates will be provided at all.

We recommend migrating to the Infinity datasource. Here are the [migration steps](https://github.com/grafana/grafana-infinity-datasource/discussions/740) you can follow.
Thank you for your understanding.
