### ISSUE TITLE
Unable to display GPS position via SimpleJSON and Geomap

### ISSUE THREAD

**Issue by MatinF** [grafana/datasource-plugin-genericdatasource#179]
I'm trying to display a set of GPS positions in the Grafana Geomap panel using SimpleJSON. My query looks as below:

```
{"device":"${DEVICE}","itf":"CAN","chn":"CH2","db":"canmod-gps","signal":"(Latitude|Longitude)"}
```

I would expect this to work as intended as it produces the two signals as timeseries (when using the TimeSeries panel), but maybe I am missing something basic to get this to work with the Geomap panel - any suggestions?

**Comment by itsgareth** [comment]
The Simple JSON Datasource is now deprecated, and as a result, we are closing all open issues in this repository.
Our development focus has shifted, and we are no longer actively maintaining this plugin.

This deprecation means that this plugin won’t receive any feature updates or bug fixes except critical security fixes.
After 6 months of the deprecation date (End of June 2024), no updates will be provided at all.

We recommend migrating to the Infinity datasource. Here are the [migration steps](https://github.com/grafana/grafana-infinity-datasource/discussions/740) you can follow.
Thank you for your understanding.
